<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // ===== STREAMING VIDEO (category_id = 1) =====
            [
                'nama_produk' => 'Netflix Premium',
                'logo' => 'netflix.jpg',
                'category_id' => 1,
                'tipe_akun' => 'sharing_user',  // ← DIGANTI
                'deskripsi' => 'Nonton film dan series tanpa iklan dengan kualitas 4K UHD',
                'harga' => 54000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 54000],
                    ['durasi' => '3 Bulan', 'harga' => 150000],
                    ['durasi' => '6 Bulan', 'harga' => 290000],
                    ['durasi' => '12 Bulan', 'harga' => 550000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Disney+ Hotstar',
                'logo' => 'disney.jpg',
                'category_id' => 1,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Konten Disney, Marvel, Star Wars, dan Pixar dalam satu platform',
                'harga' => 50000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS, Smart TV',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 50000],
                    ['durasi' => '3 Bulan', 'harga' => 140000],
                    ['durasi' => '6 Bulan', 'harga' => 270000],
                    ['durasi' => '12 Bulan', 'harga' => 500000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'YouTube Premium',
                'logo' => 'youtube.jpg',
                'category_id' => 1,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Bebas iklan, download video, dan akses YouTube Music',
                'harga' => 35000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 35000],
                    ['durasi' => '3 Bulan', 'harga' => 100000],
                    ['durasi' => '6 Bulan', 'harga' => 190000],
                    ['durasi' => '12 Bulan', 'harga' => 360000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'WeTV Premium',
                'logo' => 'wetv.jpg',
                'category_id' => 1,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Drama Asia terbaik tanpa iklan dengan subtitle Indonesia',
                'harga' => 30000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 30000],
                    ['durasi' => '3 Bulan', 'harga' => 85000],
                    ['durasi' => '6 Bulan', 'harga' => 160000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Viu Premium',
                'logo' => 'viu.jpg',
                'category_id' => 1,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Drama Korea dan variety show dengan subtitle cepat',
                'harga' => 30000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 30000],
                    ['durasi' => '3 Bulan', 'harga' => 85000],
                    ['durasi' => '6 Bulan', 'harga' => 160000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Vidio Premium',
                'logo' => 'vidio.jpg',
                'category_id' => 1,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Live sports, film Indonesia, dan series lokal original',
                'harga' => 35000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 35000],
                    ['durasi' => '3 Bulan', 'harga' => 100000],
                    ['durasi' => '6 Bulan', 'harga' => 190000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'iQIYI Premium',
                'logo' => 'iqiyi.jpg',
                'category_id' => 1,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Drama China dan Korea dengan subtitle berkualitas',
                'harga' => 35000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 35000],
                    ['durasi' => '3 Bulan', 'harga' => 100000],
                    ['durasi' => '6 Bulan', 'harga' => 190000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Bstation Premium',
                'logo' => 'bstation.jpg',
                'category_id' => 1,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Anime subtitle Indonesia dan konten kreator lokal',
                'harga' => 25000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 25000],
                    ['durasi' => '3 Bulan', 'harga' => 70000],
                    ['durasi' => '6 Bulan', 'harga' => 130000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Amazon Video',
                'logo' => 'amazon.jpg',
                'category_id' => 1,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Film Hollywood dan series original Amazon eksklusif',
                'harga' => 40000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS, Smart TV',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 40000],
                    ['durasi' => '3 Bulan', 'harga' => 110000],
                    ['durasi' => '6 Bulan', 'harga' => 210000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== STREAMING MUSIC (category_id = 2) =====
            [
                'nama_produk' => 'Spotify Premium',
                'logo' => 'spotify.jpg',
                'category_id' => 2,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Musik tanpa iklan dengan kualitas audio tinggi',
                'harga' => 25000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS, Desktop',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 25000],
                    ['durasi' => '3 Bulan', 'harga' => 70000],
                    ['durasi' => '6 Bulan', 'harga' => 130000],
                    ['durasi' => '12 Bulan', 'harga' => 240000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Webtoon',
                'logo' => 'webtoon.jpg',
                'category_id' => 2,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Baca komik favorit tanpa iklan dengan fast pass unlimited',
                'harga' => 25000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 25000],
                    ['durasi' => '3 Bulan', 'harga' => 70000],
                    ['durasi' => '6 Bulan', 'harga' => 130000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== GAME (category_id = 3) =====
            [
                'nama_produk' => 'Roblox Robux',
                'logo' => 'robux.jpg',
                'category_id' => 3,
                'tipe_akun' => 'invite_email',  // ← Game pakai invite_email
                'deskripsi' => 'Top up Robux untuk membeli item premium di Roblox',
                'harga' => 50000,
                'durasi' => 0,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Windows, Mac, Android, iOS, Xbox',
                'paket_harga' => json_encode([
                    ['durasi' => '800 Robux', 'harga' => 40000],
                    ['durasi' => '1000 Robux', 'harga' => 50000],
                    ['durasi' => '2000 Robux', 'harga' => 95000],
                    ['durasi' => '5000 Robux', 'harga' => 230000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== CLOUD STORAGE (category_id = 4) =====
            [
                'nama_produk' => 'Google',
                'logo' => 'gdrive.jpg',
                'category_id' => 4,
                'tipe_akun' => 'invite_email',
                'deskripsi' => 'Penyimpanan cloud aman untuk file dan foto',
                'harga' => 30000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS, Desktop',
                'paket_harga' => json_encode([
                    ['durasi' => '100GB 1 Bulan', 'harga' => 30000],
                    ['durasi' => '100GB 3 Bulan', 'harga' => 85000],
                    ['durasi' => '200GB 1 Bulan', 'harga' => 45000],
                    ['durasi' => '2TB 1 Bulan', 'harga' => 150000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== PRODUCTIVITY (category_id = 5) =====
            [
                'nama_produk' => 'Canva Pro',
                'logo' => 'canva.jpg',
                'category_id' => 5,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Desain grafis profesional dengan template premium unlimited',
                'harga' => 40000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS, Desktop',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 40000],
                    ['durasi' => '3 Bulan', 'harga' => 110000],
                    ['durasi' => '6 Bulan', 'harga' => 210000],
                    ['durasi' => '12 Bulan', 'harga' => 400000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'CapCut Pro',
                'logo' => 'capcut.jpg',
                'category_id' => 5,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Video editor dengan AI dan template premium tanpa watermark',
                'harga' => 20000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 20000],
                    ['durasi' => '3 Bulan', 'harga' => 55000],
                    ['durasi' => '6 Bulan', 'harga' => 100000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Alight Motion Pro',
                'logo' => 'alightmotion.jpg',
                'category_id' => 5,
                'tipe_akun' => 'sharing_user',
                'deskripsi' => 'Motion graphics dan animasi profesional untuk mobile',
                'harga' => 15000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 15000],
                    ['durasi' => '3 Bulan', 'harga' => 40000],
                    ['durasi' => '6 Bulan', 'harga' => 75000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== AI TOOLS (category_id = 6) =====
            [
                'nama_produk' => 'ChatGPT Plus',
                'logo' => 'chatgpt.jpg',
                'category_id' => 6,
                'tipe_akun' => 'invite_email',
                'deskripsi' => 'Akses GPT-4 dengan respons prioritas dan unlimited query',
                'harga' => 200000,
                'durasi' => 30,
                'stok' => 100,
                'status' => 'tersedia',
                'platform' => 'Web, Android, iOS',
                'paket_harga' => json_encode([
                    ['durasi' => '1 Bulan', 'harga' => 200000],
                    ['durasi' => '3 Bulan', 'harga' => 570000],
                    ['durasi' => '6 Bulan', 'harga' => 1100000],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
    'nama_produk' => 'Perplexity Pro',
    'logo' => 'perplexity.jpg',
    'category_id' => 6,
    'tipe_akun' => 'invite_email',
    'deskripsi' => 'AI search engine dengan sumber terpercaya dan unlimited searches',
    'harga' => 250000,
    'durasi' => 30,
    'stok' => 100,
    'status' => 'tersedia',
    'platform' => 'Web, Android, iOS, Desktop',
    'paket_harga' => json_encode([
        ['durasi' => '1 Bulan', 'harga' => 250000],
        ['durasi' => '3 Bulan', 'harga' => 700000],
        ['durasi' => '6 Bulan', 'harga' => 1350000],
        ['durasi' => '12 Bulan', 'harga' => 2500000],
    ]),
    'created_at' => now(),
    'updated_at' => now(),
],
        ];

        // Insert semua data produk
        DB::table('products')->insert($products);
    }
}
